# APPLICATION PROPERTIES
spring.application.name=intare_hotel

# DATABASE CONFIGURATIONS PROPERTIES
spring.datasource.url=jdbc:postgresql://localhost:5432/intare_hotel
spring.datasource.username=postgres
spring.datasource.password=beni@ish1
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver

# JWT CONFIGURATION PROPERTIES
jwt.secret.key=!232@asdf45wqewce3W4E2@3&23!320prdfsvawer(#